# Generated by Django 5.2.6 on 2025-10-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image_product_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(blank=True, help_text="Product dimensions (e.g., '21cm x 14.8cm' or '15cm L x 10cm W x 2cm H')", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams (g)', max_digits=8, null=True),
        ),
    ]
