# Generated by Django 5.2.6 on 2025-10-18 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_dimensions_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the product name (auto-generated)', max_length=250, null=True),
        ),
    ]
