# Generated by Django 5.2.6 on 2025-11-01 12:30

import shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_populate_slugs_before_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Upload a profile picture', null=True, upload_to=shop.models.profile_picture_upload_path),
        ),
    ]