# Generated by Django 5.2.6 on 2025-11-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='preferred_currency',
            field=models.CharField(choices=[('PHP', 'Philippine Peso (₱)'), ('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)')], default='PHP', help_text='Preferred currency for pricing', max_length=3),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('CREDIT_CARD', 'Credit Card'), ('PAYPAL', 'PayPal'), ('GCASH', 'GCash')], default='COD', help_text='Preferred payment method', max_length=20),
        ),
    ]