# Generated by Django 5.2.7 on 2025-11-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('Philippines', 'Philippines'), ('United States', 'United States'), ('Canada', 'Canada'), ('United Kingdom', 'United Kingdom'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('Singapore', 'Singapore'), ('Malaysia', 'Malaysia'), ('Thailand', 'Thailand'), ('Indonesia', 'Indonesia'), ('Vietnam', 'Vietnam'), ('India', 'India'), ('China', 'China'), ('Hong Kong', 'Hong Kong'), ('Taiwan', 'Taiwan'), ('Germany', 'Germany'), ('France', 'France'), ('Italy', 'Italy'), ('Spain', 'Spain'), ('Netherlands', 'Netherlands'), ('Belgium', 'Belgium'), ('Switzerland', 'Switzerland'), ('Austria', 'Austria'), ('Sweden', 'Sweden'), ('Norway', 'Norway'), ('Denmark', 'Denmark'), ('Finland', 'Finland'), ('Brazil', 'Brazil'), ('Mexico', 'Mexico'), ('Argentina', 'Argentina'), ('Chile', 'Chile'), ('Colombia', 'Colombia'), ('Peru', 'Peru'), ('New Zealand', 'New Zealand'), ('South Africa', 'South Africa'), ('United Arab Emirates', 'United Arab Emirates'), ('Saudi Arabia', 'Saudi Arabia'), ('Israel', 'Israel'), ('Turkey', 'Turkey'), ('Russia', 'Russia'), ('Other', 'Other')], default='Philippines', max_length=100),
        ),
    ]
