# Generated by Django 5.2.6 on 2025-11-02 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_orderitem'),
        ('shop', '0010_alter_address_country'),
    ]

    operations = [
    ]
